name: Rotate QR Access Passwords

on:
  schedule:
    - cron: '0 2 * * *'  # jeden Tag um 2:00 Uhr UTC (also 4:00 Uhr morgens in Deutschland)
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger password rotation API
        run: curl -X POST https://meinlohn.app/api/team/rotate-all-access-passwords -H "x-api-key: ${{ secrets.CRON_KEY }}"
