# .github/workflows/rotate-passwords.yml
name: Rotate QR Access Passwords

on:
  schedule:
    - cron: '0 2 * * *'  # täglich um 2:00 Uhr UTC (4:00 deutscher Zeit)
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger password rotation API
        run: |
          curl -X POST https://meinlohn.app/api/team/rotate-all-access-passwords \
            -H "x-api-key: ${{ secrets.CRON_KEY }}"
